name: Test library

on:
  push:
    branches: ["main","turbo"]

jobs:
  build-typescale-library:
    name: "Build typescale-library"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run test
